Flake8:
  script:
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/prepare-and-run-flake8.sh
  - ". ./prepare-and-run-flake8.sh pytools test"
  tags:
  - python3
  except:
  - tags

