jobs:
-
    job: 'Flake8'
    pool:
        vmImage: 'ubuntu-16.04'
    strategy:
        matrix:
            Python36:
                python.version: '3.7'

    steps:
    -
        task: UsePythonVersion@0
        inputs:
            versionSpec: '$(python.version)'

    -
        script: |
            set -e
            curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/prepare-and-run-flake8.sh
            . ./prepare-and-run-flake8.sh modepy test

        displayName: 'Flake8'
